/**:
  ros__parameters:
    robot_description_planning:
      # [ARQUIVO NOVO] Limites Físicos e Dinâmicos das Juntas para o MoveIt
      # O planejador de trajetórias vai ler esse arquivo para garantir que as juntas não ultrapassem essas velocidades/acelerações,
      # gerando assim movimentos suaves que o controlador consegue seguir sem dar solavancos.

      # DEFINIÇÃO DOS LIMITES DE VELOCIDADE E ACELERAÇÃO ANGULARES PARA CADA UMA DAS JUNTAS
      joint_limits:
        # Limites para a primeira junta da base
        base_second_joint:
          has_velocity_limits: true
          max_velocity: 0.1     # Velocidade máxima em rad/s
          has_acceleration_limits: true
          max_acceleration: 0.5 # Aceleração máxima em rad/s²

        # Limites para a segunda junta
        second_third_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5

        # Limites para a terceira junta
        third_fourth_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5

        # Limites para a junta do pulso (mão)
        fourth_hand_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5

        # Limites para o dedo direito da garra
        hand_right_gripper_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5

        # Limites para o dedo esquerdo da garra
        hand_left_gripper_joint:
          has_velocity_limits: true
          max_velocity: 0.1
          has_acceleration_limits: true
          max_acceleration: 0.5
