/**:
  ros__parameters:
    # [ARQUIVO NOVO] Configuração dos controladores que o MoveIt usará para comandar o robô
    # moveit_simple_controller_manager é o gerenciador padrão do MoveIt para enviar comandos de trajetória
    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      # Lista dos controladores ativos do ros2_control que o MoveIt pode controlar
      controller_names:
        - arm_controller
        - gripper_controller

      # Configuração do controlador do braço
      arm_controller:
        type: FollowJointTrajectory # Tipo de ação ROS para seguir trajetórias de juntas
        action_ns: follow_joint_trajectory # Namespace da action server
        default: true
        # Juntas que pertencem a este controlador
        joints:
          - base_second_joint
          - second_third_joint
          - third_fourth_joint
          - fourth_hand_joint

      # Configuração do controlador da garra
      gripper_controller:
        type: FollowJointTrajectory
        action_ns: follow_joint_trajectory
        default: true
        # Juntas da garra
        joints:
          - hand_right_gripper_joint
          - hand_left_gripper_joint
